# Generated by Django 5.0.4 on 2024-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('shortname', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('marketcap', models.BigIntegerField()),
                ('previous_close', models.FloatField()),
                ('beta', models.FloatField()),
                ('baw', models.FloatField()),
                ('amin', models.FloatField()),
                ('amax', models.FloatField()),
                ('correlation', models.FloatField()),
            ],
        ),
    ]
